__all__ = ["LABELED_PHRASES"]

type LabeledPhrases = dict[
  str,
  list[str | tuple[str, str]]
]

LABELED_PHRASES: LabeledPhrases = {
  "DEV": [
    "admin",
    "analyst",
    "architect",
    "coder",
    ("coding", "VERB"),
    ("developing", "VERB"),
    ("programming", "VERB"),
    "dba", # DB admin
    "dev",
    "dev=op(s)",
    "developer",
    "development",
    "eng",
    "engineer",
    "engineering",
    "gopher",
    "hacker",
    "investigator",
    "mathematician",
    "ml=op(s)",
    "op(s)",
    "pentester",
    "ph.d",
    "pythonist(a)",
    "programmer",
    "qa",
    "rustacean",
    "researcher",
    "scientist",
    "sec",
    "sec=op(s)",
    "sde",
    "swe",
    "tester",
  ],
  "FREELANCER": [
    "free=lance(r)",
    "free=lancing",
    "consultant",
    "consulting",
  ],
  "LEAD": [
    "lead",
    "leader",
    ("leading", "VERB"),
    "leadership",
    "teamlead",
    "techlead",
    "tl",
  ],
  "ORG": [
    "agency",
    "company",
    "community",
    "organization",
    "platform",
    "professional network",
    "social network",
    "firm",
  ],
  "NONDEV": [
    "academic",
    "ceo",
    "coach",
    "cofounder",
    "co-founder",
    "cto",
    "dean",
    "designer",
    ("designing", "VERB"),
    "director",
    "educator",
    "entrepreneur",
    "founder",
    ("founding", "VERB"),
    "head",
    ("hiring", "VERB"),
    "investor",
    "lawyer",
    "lecturer",
    ("lecturing", "VERB"),
    "owner",
    "president",
    "producer",
    ("producing", "VERB"),
    "prof",
    "professor",
    "postdoc",
    "manager",
    ("managing", "VERB"),
    "mentor",
    ("mentoring", "VERB"),
    "recruiter",
    ("recruiting", "VERB"),
    "svp",
    "teacher",
    ("teaching", "VERB"),
    "vp",
  ],
  "STUDENT": [
    "alumni",
    "alumnus",
    "beginner",
    "graduate",
    "bachelor",
    "b.s",
    "freshman",
    "intern",
    "internship",
    "master of science",
    "m.s",
    "major",
    "learner",
    ("learn", "VERB"),
    ("learning", "VERB"),
    "newbie",
    "new to",
    "noob",
    "novice",
    "rookie",
    "sophomore",
    "student",
    ("study", "VERB"),
    ("studying", "VERB"),
    "teenager",
    "undergrad(uate)",
  ],
  "REMOTE": [
    "remote",
    "remotely",
  ],
}

# ("specialist", "generalist", "guru", "expert", "ninja", "magician", "professional", "wizard") were previously used
# to cancel "Student" role. Not applied yet, not sure...
# ("artist", "mechanic", "musician", "physicist") were previously used
# to cancel "Dev" role. Not applied yet, not sure...
